### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by Jonathan0827** [retromp3/retro#20]
Spotify Not Working.

**Comment by fritzlb** [comment]
This is a known issue. The Spotify api requires that the bundle ID registered with Apple is also registered with their developer portal. 
Because Sakun registered the bundle ID for retro by installing the beta onto his phone, nobody else is able to register it with Apple. The Spotify API detects this and blocks access attempts. 

Workaround: add your own Spotify api keys to the source code before compiling and deploying with Xcode.

**Comment by sakofchit** [comment]
@fritzlb is correct and that's probably the only workaround afiak. Alternatively wait for the new TestFlight
